resolver: lts-22.6

packages:
- .

extra-deps:
- categories-1.0.7
- kan-extensions-5.2.5
- adjunctions-4.4.2
- free-5.2
- comonad-5.0.8
- distributive-0.6.2.1
- profunctors-5.6.2
- semigroupoids-6.0.0.1
- bifunctors-5.6.2
- tagged-0.8.8
- groups-0.5.3

flags: {}

extra-package-dbs: []